SELF_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
BASEDIR := $(SELF_DIR)..

# Amiga OS toolchain
TOOLCHAIN_AMIGAOS_PREFIX = /opt/amiga

CC_AMIGAOS = $(TOOLCHAIN_AMIGAOS_PREFIX)/bin/m68k-amigaos-gcc
AS_AMIGAOS = $(TOOLCHAIN_AMIGAOS_PREFIX)/bin/m68k-amigaos-as
LD_AMIGAOS = $(TOOLCHAIN_AMIGAOS_PREFIX)/bin/m68k-amigaos-ld
AR_AMIGAOS = $(TOOLCHAIN_AMIGAOS_PREFIX)/bin/m68k-amigaos-ar
STRIP_AMIGAOS = $(TOOLCHAIN_AMIGAOS_PREFIX)/bin/m68k-amigaos-strip
OBJDUMP_AMIGAOS = $(TOOLCHAIN_AMIGAOS_PREFIX)/bin/m68k-amigaos-objdump
OBJCOPY_AMIGAOS = $(TOOLCHAIN_AMIGAOS_PREFIX)/bin/m68k-amigaos-objcopy

# Paths - use build directory structure
LXA_BIN = $(BASEDIR)/build/host/bin/lxa
LXA_ROM = $(BASEDIR)/build/target/rom/lxa.rom
LXA_SYS = $(BASEDIR)/build/target/sys
