/*
 * lxa_images.c - Intuition's built-in BOOPSI image classes (Phase 223):
 * imageclass, sysiclass and frameiclass, plus the drawing helpers the
 * window chrome, the screen bar and GadTools share with them.
 *
 * Appearance is taken from real AmigaOS 3.1 (reference-driven development):
 *  - sysiclass images are table driven (lxa_sysi_data.h, generated by
 *    tools/rdd/sysitable.py from the rendering gallery reference);
 *  - frameiclass frames follow the edge rules observed in the frame gallery
 *    (tests/scenarios/gallery-frames.yaml).
 */

#include <exec/types.h>
#include <exec/memory.h>
#include <clib/exec_protos.h>
#include <inline/exec.h>

#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/screens.h>

#include <graphics/gfx.h>
#include <graphics/rastport.h>
#include <graphics/clip.h>
#include <graphics/gfxmacros.h>
#include <clib/graphics_protos.h>
#include <inline/graphics.h>

#include <utility/tagitem.h>
#include <clib/utility_protos.h>
#include <inline/utility.h>

#include "util.h"
#include "lxa_images.h"
#include "lxa_sysi_data.h"

extern struct GfxBase *GfxBase;
extern struct UtilityBase *UtilityBase;
extern struct ExecBase *SysBase;

/* pens used when no DrawInfo is available: the Workbench 3.1 defaults */
static const UWORD g_default_pens[NUMDRIPENS + 1] = {
    0, 1, 1, 2, 1, 3, 1, 0, 2, 1, 2, 1, 1, (UWORD)~0
};

const UWORD *lxa_default_pens(void)
{
    return g_default_pens;
}

static const UWORD *pens_of(const struct DrawInfo *dri)
{
    return (dri && dri->dri_Pens) ? dri->dri_Pens : g_default_pens;
}

/* ------------------------------------------------------------------------ */
/* sysiclass images                                                          */
/* ------------------------------------------------------------------------ */

static const struct LXASysIEntry *sysi_entry(UWORD which, UWORD size)
{
    UWORD i;

    if (size > SYSISIZE_HIRES)
        size = SYSISIZE_MEDRES;
    for (i = 0; i < sizeof(g_sysi_entries) / sizeof(g_sysi_entries[0]); i++)
        if (g_sysi_entries[i].which == which && g_sysi_entries[i].size == size)
            return &g_sysi_entries[i];
    return NULL;
}

BOOL lxa_sysi_dims(UWORD which, UWORD size, UWORD *width, UWORD *height)
{
    const struct LXASysIEntry *e = sysi_entry(which, size);

    if (!e)
        return FALSE;
    if (width)
        *width = e->width;
    if (height)
        *height = e->height;
    return TRUE;
}

static UWORD state_index(ULONG state)
{
    switch (state)
    {
        case IDS_SELECTED:
        case IDS_INACTIVESELECTED:
        case IDS_SELECTEDDISABLED:
            return 1;
        case IDS_INACTIVENORMAL:
        case IDS_INACTIVEDISABLED:
            return 2;
        case IDS_DISABLED:
            return 3;
        default:
            return 0;
    }
}

BOOL lxa_sysi_draw(struct RastPort *rp, UWORD which, UWORD size, WORD x, WORD y,
                   ULONG state, const UWORD *pens)
{
    const struct LXASysIEntry *e = sysi_entry(which, size);
    const UBYTE *p;
    WORD w, h, px, py;
    UBYTE oldpen;

    if (!rp || !e)
        return FALSE;
    if (!pens)
        pens = g_default_pens;

    w = e->dw;
    h = e->dh;
    x += e->dx;
    y += e->dy;
    p = &g_sysi_pixels[g_sysi_offsets[e->state[state_index(state)]]];
    oldpen = rp->FgPen;
    px = 0;
    py = 0;
    while (py < h)
    {
        UBYTE code = *p++;
        WORD run = code >> 3;
        UBYTE role = code & 7;

        while (run > 0 && py < h)
        {
            WORD n = w - px;

            if (n > run)
                n = run;
            if (role)
            {
                UWORD pen;
                switch (role)
                {
                    case 1: pen = pens[BACKGROUNDPEN]; break;
                    case 2: pen = pens[SHINEPEN]; break;
                    case 3: pen = pens[SHADOWPEN]; break;
                    case 4: pen = pens[FILLPEN]; break;
                    case 5: pen = pens[BARDETAILPEN]; break;
                    default: pen = pens[BARBLOCKPEN]; break;
                }
                SetAPen(rp, pen);
                RectFill(rp, x + px, y + py, x + px + n - 1, y + py);
            }
            px += n;
            run -= n;
            if (px >= w)
            {
                px = 0;
                py++;
            }
        }
    }
    SetAPen(rp, oldpen);
    return TRUE;
}

/* ------------------------------------------------------------------------ */
/* frames (frameiclass, DrawBevelBox, GadTools)                              */
/* ------------------------------------------------------------------------ */

static void hline(struct RastPort *rp, WORD x0, WORD x1, WORD y)
{
    if (x1 >= x0)
        RectFill(rp, x0, y, x1, y);
}

static void vline(struct RastPort *rp, WORD x, WORD y0, WORD y1)
{
    if (y1 >= y0)
        RectFill(rp, x, y0, x, y1);
}

/* 3.1 "button" edge: two pixels wide at the sides, one at top and bottom. */
static void button_edge(struct RastPort *rp, WORD x, WORD y, WORD w, WORD h, UWORD tl, UWORD br)
{
    if (w < 2 || h < 2)
        return;
    SetAPen(rp, tl);
    hline(rp, x, x + w - 2, y);
    vline(rp, x, y, y + h - 1);
    vline(rp, x + 1, y + 1, y + h - 2);
    SetAPen(rp, br);
    vline(rp, x + w - 1, y, y + h - 1);
    hline(rp, x + 1, x + w - 1, y + h - 1);
    vline(rp, x + w - 2, y + 1, y + h - 2);
}

void lxa_draw_frame(struct RastPort *rp, ULONG type, BOOL recessed, WORD x, WORD y,
                    WORD w, WORD h, ULONG state, BOOL edges_only, const UWORD *pens)
{
    UWORD shine, shadow, t;
    BOOL selected = (state == IDS_SELECTED || state == IDS_INACTIVESELECTED ||
                     state == IDS_SELECTEDDISABLED);
    UBYTE oldpen;

    if (!rp || w <= 0 || h <= 0)
        return;
    if (!pens)
        pens = g_default_pens;
    oldpen = rp->FgPen;
    shine = pens[SHINEPEN];
    shadow = pens[SHADOWPEN];
    if (recessed)
    {
        t = shine; shine = shadow; shadow = t;
    }
    if (selected)
    {
        t = shine; shine = shadow; shadow = t;
    }

    switch (type)
    {
        case FRAME_BUTTON:
            if (!edges_only)
            {
                SetAPen(rp, selected ? pens[FILLPEN] : pens[BACKGROUNDPEN]);
                if (w > 4 && h > 2)
                    RectFill(rp, x + 2, y + 1, x + w - 3, y + h - 2);
            }
            button_edge(rp, x, y, w, h, shine, shadow);
            break;

        case FRAME_RIDGE:
            if (!edges_only)
            {
                SetAPen(rp, selected ? pens[FILLPEN] : pens[BACKGROUNDPEN]);
                if (w > 8 && h > 4)
                    RectFill(rp, x + 4, y + 2, x + w - 5, y + h - 3);
            }
            button_edge(rp, x, y, w, h, shine, shadow);
            button_edge(rp, x + 2, y + 1, w - 4, h - 2, shadow, shine);
            break;

        case FRAME_ICONDROPBOX:
            if (!edges_only)
            {
                SetAPen(rp, selected ? pens[FILLPEN] : pens[BACKGROUNDPEN]);
                if (w > 12 && h > 6)
                    RectFill(rp, x + 6, y + 3, x + w - 7, y + h - 4);
            }
            button_edge(rp, x, y, w, h, shine, shadow);
            button_edge(rp, x + 4, y + 2, w - 8, h - 4, shadow, shine);
            break;

        default:    /* FRAME_DEFAULT */
            if (!edges_only)
            {
                SetAPen(rp, selected ? pens[FILLPEN] : pens[BACKGROUNDPEN]);
                if (w > 2 && h > 2)
                    RectFill(rp, x + 1, y + 1, x + w - 2, y + h - 2);
            }
            SetAPen(rp, shine);
            hline(rp, x, x + w - 2, y);
            vline(rp, x, y, y + h - 2);
            SetAPen(rp, shadow);
            vline(rp, x + w - 1, y + 1, y + h - 1);
            hline(rp, x + 1, x + w - 1, y + h - 1);
            break;
    }
    SetAPen(rp, oldpen);
}

/*
 * Ghosting of disabled gadgets: AmigaOS 3.1 overlays a sparse dot pattern
 * in BLOCKPEN (one dot every four pixels, alternate rows offset by two),
 * aligned to the screen bitmap: 0x1111 on even, 0x4444 on odd screen rows.
 */
void lxa_ghost_rect(struct RastPort *rp, WORD x0, WORD y0, WORD x1, WORD y1, const UWORD *pens)
{
    UWORD pat[1];
    UWORD *oldpat;
    BYTE oldsz;
    UBYTE oldpen, olddm;
    WORD y, oy;

    if (!rp || x1 < x0 || y1 < y0)
        return;
    if (!pens)
        pens = g_default_pens;
    oldpat = rp->AreaPtrn;
    oldsz = rp->AreaPtSz;
    oldpen = rp->FgPen;
    olddm = rp->DrawMode;
    oy = rp->Layer ? rp->Layer->bounds.MinY - rp->Layer->Scroll_Y : 0;
    SetAPen(rp, pens[BLOCKPEN]);
    SetDrMd(rp, JAM1);
    for (y = y0; y <= y1; y++)
    {
        pat[0] = ((y + oy) & 1) ? 0x4444 : 0x1111;
        SetAfPt(rp, pat, 0);
        RectFill(rp, x0, y, x1, y);
    }
    SetAfPt(rp, oldpat, oldsz);
    SetAPen(rp, oldpen);
    SetDrMd(rp, olddm);
}

/* number of characters of s (len) that fit into width pixels */
WORD lxa_text_fit(struct RastPort *rp, CONST_STRPTR s, WORD len, WORD width)
{
    WORD n = 0, w = 0;

    if (!rp || !s)
        return 0;
    while (n < len)
    {
        WORD cw = TextLength(rp, (STRPTR)s + n, 1);
        if (w + cw > width)
            break;
        w += cw;
        n++;
    }
    return n;
}

/* frame thickness (horizontal, vertical) per FRAME_* type */
void lxa_frame_thickness(ULONG type, WORD *hthick, WORD *vthick)
{
    WORD hh, vv;

    switch (type)
    {
        case FRAME_BUTTON:      hh = 2; vv = 1; break;
        case FRAME_RIDGE:       hh = 4; vv = 2; break;
        case FRAME_ICONDROPBOX: hh = 6; vv = 3; break;
        default:                hh = 1; vv = 1; break;
    }
    if (hthick)
        *hthick = hh;
    if (vthick)
        *vthick = vv;
}

/* ------------------------------------------------------------------------ */
/* BOOPSI dispatchers                                                        */
/* ------------------------------------------------------------------------ */

static ULONG do_super(struct IClass *cl, Object *obj, Msg msg)
{
    struct IClass *super = cl->cl_Super;
    typedef ULONG (*DispatchEntry)(register struct IClass *cl __asm("a0"),
                                   register Object *obj __asm("a2"),
                                   register Msg msg __asm("a1"));

    if (!super || !super->cl_Dispatcher.h_Entry)
        return 0;
    return ((DispatchEntry)super->cl_Dispatcher.h_Entry)(super, obj, msg);
}

/* imageclass: the Image structure is the instance data */
static void image_set(struct Image *im, struct TagItem *tags)
{
    struct TagItem *ts = tags, *tag;

    while ((tag = NextTagItem(&ts)))
    {
        switch (tag->ti_Tag)
        {
            case IA_Left:   im->LeftEdge = (WORD)tag->ti_Data; break;
            case IA_Top:    im->TopEdge = (WORD)tag->ti_Data; break;
            case IA_Width:  im->Width = (WORD)tag->ti_Data; break;
            case IA_Height: im->Height = (WORD)tag->ti_Data; break;
            case IA_FGPen:  im->PlanePick = (UBYTE)tag->ti_Data; break;
            case IA_BGPen:  im->PlaneOnOff = (UBYTE)tag->ti_Data; break;
            case IA_Data:   im->ImageData = (UWORD *)tag->ti_Data; break;
            default: break;
        }
    }
}

ULONG lxa_imageclass_dispatch(register struct IClass *cl __asm("a0"),
                              register Object *obj __asm("a2"),
                              register Msg msg __asm("a1"))
{
    struct Image *im = (struct Image *)obj;

    switch (msg->MethodID)
    {
        case OM_NEW:
            obj = (Object *)do_super(cl, obj, msg);
            if (obj)
            {
                im = (struct Image *)obj;
                im->Depth = CUSTOMIMAGEDEPTH;
                im->PlanePick = 1;      /* IA_FGPen default */
                im->PlaneOnOff = 0;     /* IA_BGPen default */
                image_set(im, ((struct opSet *)msg)->ops_AttrList);
            }
            return (ULONG)obj;

        case OM_SET:
        case OM_UPDATE:
            image_set(im, ((struct opSet *)msg)->ops_AttrList);
            return 1;

        case OM_GET:
        {
            struct opGet *og = (struct opGet *)msg;
            switch (og->opg_AttrID)
            {
                case IA_Left:   *og->opg_Storage = (ULONG)(LONG)im->LeftEdge; return 1;
                case IA_Top:    *og->opg_Storage = (ULONG)(LONG)im->TopEdge; return 1;
                case IA_Width:  *og->opg_Storage = (ULONG)(LONG)im->Width; return 1;
                case IA_Height: *og->opg_Storage = (ULONG)(LONG)im->Height; return 1;
                case IA_FGPen:  *og->opg_Storage = im->PlanePick; return 1;
                case IA_BGPen:  *og->opg_Storage = im->PlaneOnOff; return 1;
                case IA_Data:   *og->opg_Storage = (ULONG)im->ImageData; return 1;
            }
            return do_super(cl, obj, msg);
        }

        case IM_DRAW:
        case IM_DRAWFRAME:
            return 0;

        case IM_ERASE:
        case IM_ERASEFRAME:
        {
            struct impErase *ie = (struct impErase *)msg;
            WORD w = im->Width, h = im->Height;
            WORD x = ie->imp_Offset.X + im->LeftEdge, y = ie->imp_Offset.Y + im->TopEdge;

            if (msg->MethodID == IM_ERASEFRAME)
            {
                w = ie->imp_Dimensions.Width;
                h = ie->imp_Dimensions.Height;
            }
            if (ie->imp_RPort && w > 0 && h > 0)
                EraseRect(ie->imp_RPort, x, y, x + w - 1, y + h - 1);
            return 1;
        }

        case IM_HITTEST:
        case IM_HITFRAME:
        {
            struct impHitTest *ih = (struct impHitTest *)msg;
            WORD w = im->Width, h = im->Height;
            WORD px = ih->imp_Point.X - im->LeftEdge, py = ih->imp_Point.Y - im->TopEdge;

            if (msg->MethodID == IM_HITFRAME)
            {
                w = ih->imp_Dimensions.Width;
                h = ih->imp_Dimensions.Height;
            }
            return (px >= 0 && py >= 0 && px < w && py < h) ? TRUE : FALSE;
        }

        default:
            return do_super(cl, obj, msg);
    }
}

/* sysiclass */
struct SysIData
{
    UWORD which;
    UWORD size;
    struct DrawInfo *dri;
};

const ULONG lxa_sysiclass_instsize = sizeof(struct SysIData);

ULONG lxa_sysiclass_dispatch(register struct IClass *cl __asm("a0"),
                             register Object *obj __asm("a2"),
                             register Msg msg __asm("a1"))
{
    struct SysIData *sd;
    struct Image *im;

    switch (msg->MethodID)
    {
        case OM_NEW:
        {
            struct TagItem *tags = ((struct opSet *)msg)->ops_AttrList;
            UWORD w = 0, h = 0;

            obj = (Object *)do_super(cl, obj, msg);
            if (!obj)
                return 0;
            sd = INST_DATA(cl, obj);
            im = (struct Image *)obj;
            sd->which = (UWORD)GetTagData(SYSIA_Which, (ULONG)~0, tags);
            sd->size = (UWORD)GetTagData(SYSIA_Size, SYSISIZE_MEDRES, tags);
            sd->dri = (struct DrawInfo *)GetTagData(SYSIA_DrawInfo, 0, tags);
            if (!lxa_sysi_dims(sd->which, sd->size, &w, &h))
            {
                /* AmigaOS 3.1: unknown SYSIA_Which values fail */
                struct { ULONG MethodID; } dm = { OM_DISPOSE };
                do_super(cl, obj, (Msg)&dm);
                return 0;
            }
            /* IA_Width/IA_Height given by the caller win */
            if (!FindTagItem(IA_Width, tags))
                im->Width = w;
            if (!FindTagItem(IA_Height, tags))
                im->Height = h;
            return (ULONG)obj;
        }

        case IM_DRAW:
        case IM_DRAWFRAME:
        {
            struct impDraw *id = (struct impDraw *)msg;
            const struct DrawInfo *dri = id->imp_DrInfo ? id->imp_DrInfo : NULL;

            sd = INST_DATA(cl, obj);
            im = (struct Image *)obj;
            if (!dri)
                dri = sd->dri;
            lxa_sysi_draw(id->imp_RPort, sd->which, sd->size,
                          id->imp_Offset.X + im->LeftEdge, id->imp_Offset.Y + im->TopEdge,
                          id->imp_State, pens_of(dri));
            return 1;
        }

        default:
            return do_super(cl, obj, msg);
    }
}

/* frameiclass */
struct FrameIData
{
    ULONG type;
    BOOL recessed;
    BOOL edges_only;
};

const ULONG lxa_frameiclass_instsize = sizeof(struct FrameIData);

static void frame_set(struct FrameIData *fd, struct TagItem *tags)
{
    struct TagItem *ts = tags, *tag;

    while ((tag = NextTagItem(&ts)))
    {
        switch (tag->ti_Tag)
        {
            case IA_FrameType: fd->type = tag->ti_Data; break;
            case IA_Recessed:  fd->recessed = tag->ti_Data ? TRUE : FALSE; break;
            case IA_EdgesOnly: fd->edges_only = tag->ti_Data ? TRUE : FALSE; break;
            default: break;
        }
    }
}

ULONG lxa_frameiclass_dispatch(register struct IClass *cl __asm("a0"),
                               register Object *obj __asm("a2"),
                               register Msg msg __asm("a1"))
{
    struct FrameIData *fd;
    struct Image *im;

    switch (msg->MethodID)
    {
        case OM_NEW:
            obj = (Object *)do_super(cl, obj, msg);
            if (obj)
            {
                fd = INST_DATA(cl, obj);
                fd->type = FRAME_DEFAULT;
                frame_set(fd, ((struct opSet *)msg)->ops_AttrList);
            }
            return (ULONG)obj;

        case OM_SET:
        case OM_UPDATE:
            fd = INST_DATA(cl, obj);
            frame_set(fd, ((struct opSet *)msg)->ops_AttrList);
            return do_super(cl, obj, msg);

        case IM_DRAW:
        case IM_DRAWFRAME:
        {
            struct impDraw *id = (struct impDraw *)msg;
            WORD w, h;

            fd = INST_DATA(cl, obj);
            im = (struct Image *)obj;
            w = im->Width;
            h = im->Height;
            if (msg->MethodID == IM_DRAWFRAME)
            {
                w = id->imp_Dimensions.Width;
                h = id->imp_Dimensions.Height;
            }
            lxa_draw_frame(id->imp_RPort, fd->type, fd->recessed,
                           id->imp_Offset.X + im->LeftEdge, id->imp_Offset.Y + im->TopEdge,
                           w, h, id->imp_State, fd->edges_only, pens_of(id->imp_DrInfo));
            return 1;
        }

        case IM_FRAMEBOX:
        {
            struct impFrameBox *fb = (struct impFrameBox *)msg;
            WORD hh, vv;

            fd = INST_DATA(cl, obj);
            lxa_frame_thickness(fd->type, &hh, &vv);
            fb->imp_FrameBox->Left = fb->imp_ContentsBox->Left - hh;
            fb->imp_FrameBox->Top = fb->imp_ContentsBox->Top - vv;
            fb->imp_FrameBox->Width = fb->imp_ContentsBox->Width + 2 * hh;
            fb->imp_FrameBox->Height = fb->imp_ContentsBox->Height + 2 * vv;
            return 1;
        }

        default:
            return do_super(cl, obj, msg);
    }
}
