/*
 * lxa_rdd.c - snapshot-bundle parity with the reference agent (Phase 212)
 *
 * Produces the same raw artefacts as tools/refsys/agent/lxaprobe.c does on
 * real AmigaOS, so the RDD comparator sees one format from both backends:
 *
 *   lxa_dump_tree_json()          <-> DUMP_TREE   (schema lxa-tree/1)
 *   lxa_capture_screen_indexed()  <-> SNAP        (LXASNAP1)
 *   lxa_capture_window_indexed()  <-> SNAP WINDOW n
 *   lxa_text_log_*()              <-> TEXT_START / TEXT_DUMP
 *
 * Everything is read from emulated memory with NDK offsets generated by
 * tools/gen_ndk_offsets.py; no emulated cycles are spent.
 * The formats are specified in doc/rdd-snapshot.md.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "lxa_api.h"
#include "lxa_ndk_offsets.h"
#include "m68k.h"

/* m68k flag bits (NDK) */
#define GFLG_LABELMASK   0x3000
#define GFLG_LABELITEXT  0x0000
#define ITEMTEXT         0x0002
#define COMMSEQ          0x0004

extern void (*g_text_hook)(const char *str, int len, int x, int y, void *userdata);
extern void *g_text_hook_userdata;

static uint32_t rd32(uint32_t a) { return m68k_read_memory_32(a); }
static int16_t  rd16s(uint32_t a) { return (int16_t)m68k_read_memory_16(a); }
static uint16_t rd16(uint32_t a) { return (uint16_t)m68k_read_memory_16(a); }
static uint8_t  rd8(uint32_t a)  { return (uint8_t)m68k_read_memory_8(a); }
static int8_t   rd8s(uint32_t a) { return (int8_t)m68k_read_memory_8(a); }

static uint32_t intuition_base(void)
{
    uint32_t sysbase = rd32(4), node;
    if (!sysbase)
        return 0;
    /* ExecBase->LibList at 378 */
    for (node = rd32(sysbase + 378); node && rd32(node); node = rd32(node)) {
        uint32_t name = rd32(node + 10);
        char buf[24];
        int i;
        for (i = 0; i < 23 && name; i++) {
            buf[i] = (char)rd8(name + i);
            if (!buf[i])
                break;
        }
        buf[i < 23 ? i : 23] = 0;
        if (strcmp(buf, "intuition.library") == 0)
            return node;
    }
    return 0;
}

/* ------------------------------------------------------------------ */
/* JSON helpers                                                        */
/* ------------------------------------------------------------------ */

static void jstr(FILE *f, uint32_t addr)
{
    int i;
    if (!addr) {
        fputs("null", f);
        return;
    }
    fputc('"', f);
    for (i = 0; i < 1024; i++) {
        unsigned char c = rd8(addr + i);
        if (!c)
            break;
        if (c == '"' || c == '\\')
            fprintf(f, "\\%c", c);
        else if (c < 0x20)
            fprintf(f, "\\u%04x", c);
        else if (c >= 0x80)
            fprintf(f, "%c%c", 0xC0 | (c >> 6), 0x80 | (c & 0x3F));   /* Latin-1 -> UTF-8 */
        else
            fputc(c, f);
    }
    fputc('"', f);
}

static void jfont(FILE *f, uint32_t font)
{
    if (!font) {
        fputs("null", f);
        return;
    }
    fputs("{\"name\":", f);
    jstr(f, rd32(font + OFF_TF_NAME));
    fprintf(f, ",\"ysize\":%u,\"xsize\":%u,\"baseline\":%u}",
            rd16(font + OFF_TF_YSIZE), rd16(font + OFF_TF_XSIZE), rd16(font + OFF_TF_BASELINE));
}

static void jintuitext(FILE *f, uint32_t it)
{
    int first = 1, guard = 0;
    fputc('[', f);
    for (; it && guard < 64; it = rd32(it + OFF_IT_NEXT), guard++) {
        fprintf(f, "%s{\"text\":", first ? "" : ",");
        jstr(f, rd32(it + OFF_IT_TEXT));
        fprintf(f, ",\"left\":%d,\"top\":%d,\"fpen\":%u,\"bpen\":%u,\"drawmode\":%u}",
                rd16s(it + OFF_IT_LEFT), rd16s(it + OFF_IT_TOP), rd8(it + OFF_IT_FPEN),
                rd8(it + OFF_IT_BPEN), rd8(it + OFF_IT_DMODE));
        first = 0;
    }
    fputc(']', f);
}

static void jgadgets(FILE *f, uint32_t g)
{
    int first = 1, guard = 0;
    fputc('[', f);
    for (; g && guard < 1024; g = rd32(g + OFF_G_NEXT), guard++) {
        uint16_t flags = rd16(g + OFF_G_FLAGS);
        fprintf(f, "%s{\"id\":%u,\"type\":%u,\"flags\":%u,\"activation\":%u,"
                   "\"left\":%d,\"top\":%d,\"width\":%d,\"height\":%d,\"text\":",
                first ? "" : ",", rd16(g + OFF_G_ID), rd16(g + OFF_G_TYPE), flags,
                rd16(g + OFF_G_ACT), rd16s(g + OFF_G_LEFT), rd16s(g + OFF_G_TOP),
                rd16s(g + OFF_G_W), rd16s(g + OFF_G_H));
        if ((flags & GFLG_LABELMASK) == GFLG_LABELITEXT)
            jintuitext(f, rd32(g + OFF_G_TEXT));
        else
            fputs("[]", f);
        fputc('}', f);
        first = 0;
    }
    fputc(']', f);
}

static void jitems(FILE *f, uint32_t it, int depth)
{
    int first = 1, guard = 0;
    fputc('[', f);
    for (; it && guard < 256; it = rd32(it + OFF_MI_NEXT), guard++) {
        uint16_t flags = rd16(it + OFF_MI_FLAGS);
        uint32_t fill = rd32(it + OFF_MI_FILL);
        fprintf(f, "%s{\"left\":%d,\"top\":%d,\"width\":%d,\"height\":%d,\"flags\":%u,"
                   "\"mutualexclude\":%d,\"command\":%u,\"text\":",
                first ? "" : ",", rd16s(it + OFF_MI_LEFT), rd16s(it + OFF_MI_TOP),
                rd16s(it + OFF_MI_W), rd16s(it + OFF_MI_H), flags, (int32_t)rd32(it + OFF_MI_MX),
                (flags & COMMSEQ) ? rd8(it + OFF_MI_CMD) : 0);
        if ((flags & ITEMTEXT) && fill)
            jstr(f, rd32(fill + OFF_IT_TEXT));
        else
            fputs("null", f);
        fputs(",\"sub\":", f);
        if (depth == 0)
            jitems(f, rd32(it + OFF_MI_SUB), 1);
        else
            fputs("[]", f);
        fputc('}', f);
        first = 0;
    }
    fputc(']', f);
}

static void jmenus(FILE *f, uint32_t m)
{
    int first = 1, guard = 0;
    fputc('[', f);
    for (; m && guard < 64; m = rd32(m + OFF_M_NEXT), guard++) {
        fprintf(f, "%s{\"title\":", first ? "" : ",");
        jstr(f, rd32(m + OFF_M_NAME));
        fprintf(f, ",\"left\":%d,\"top\":%d,\"width\":%d,\"height\":%d,\"flags\":%u,\"items\":",
                rd16s(m + OFF_M_LEFT), rd16s(m + OFF_M_TOP), rd16s(m + OFF_M_W),
                rd16s(m + OFF_M_H), rd16(m + OFF_M_FLAGS));
        jitems(f, rd32(m + OFF_M_FIRST), 0);
        fputc('}', f);
        first = 0;
    }
    fputc(']', f);
}

static void jwindow(FILE *f, uint32_t w)
{
    uint32_t rport = rd32(w + OFF_W_RPORT);
    fputs("{\"title\":", f);
    jstr(f, rd32(w + OFF_W_TITLE));
    fputs(",\"screen_title\":", f);
    jstr(f, rd32(w + OFF_W_SCRTITLE));
    fprintf(f, ",\"app\":true,\"left\":%d,\"top\":%d,\"width\":%d,\"height\":%d,"
               "\"min_width\":%d,\"min_height\":%d,\"max_width\":%u,\"max_height\":%u,"
               "\"flags\":%u,\"idcmp\":%u,\"border\":[%d,%d,%d,%d],\"detail_pen\":%u,"
               "\"block_pen\":%u,\"font\":",
            rd16s(w + OFF_W_LEFT), rd16s(w + OFF_W_TOP), rd16s(w + OFF_W_W), rd16s(w + OFF_W_H),
            rd16s(w + OFF_W_MINW), rd16s(w + OFF_W_MINH), rd16(w + OFF_W_MAXW), rd16(w + OFF_W_MAXH),
            rd32(w + OFF_W_FLAGS), rd32(w + OFF_W_IDCMP),
            rd8s(w + OFF_W_BL), rd8s(w + OFF_W_BT), rd8s(w + OFF_W_BR), rd8s(w + OFF_W_BB),
            rd8(w + OFF_W_DETAIL), rd8(w + OFF_W_BLOCK));
    jfont(f, rport ? rd32(rport + OFF_RP_FONT) : 0);
    fputs(",\"gadgets\":", f);
    jgadgets(f, rd32(w + OFF_W_FIRSTGAD));
    fputs(",\"menus\":", f);
    jmenus(f, rd32(w + OFF_W_MENU));
    fputc('}', f);
}

int lxa_dump_tree_json(const char *path)
{
    uint32_t ib = intuition_base(), s;
    FILE *f;
    int fs = 1, guard = 0;

    if (!path)
        return -1;
    f = fopen(path, "w");
    if (!f)
        return -1;

    fputs("{\"schema\":\"lxa-tree/1\",\"backend\":\"lxa\",\"screens\":[", f);
    for (s = ib ? rd32(ib + OFF_IB_FIRSTSCR) : 0; s && guard < 32; s = rd32(s + OFF_SCR_NEXT), guard++) {
        uint32_t cm = rd32(s + OFF_SCR_VP + OFF_VP_CM);
        uint32_t w;
        int fw = 1, wguard = 0;
        fprintf(f, "%s{\"title\":", fs ? "" : ",");
        jstr(f, rd32(s + OFF_SCR_TITLE));
        fputs(",\"default_title\":", f);
        jstr(f, rd32(s + OFF_SCR_DEFTITLE));
        fprintf(f, ",\"left\":%d,\"top\":%d,\"width\":%d,\"height\":%d,\"depth\":%u,"
                   "\"display_id\":%u,\"flags\":%u,\"bar_height\":%d,\"bar_vborder\":%d,"
                   "\"bar_hborder\":%d,\"menu_vborder\":%d,\"menu_hborder\":%d,"
                   "\"wbor\":[%d,%d,%d,%d],\"font\":",
                rd16s(s + OFF_SCR_LEFT), rd16s(s + OFF_SCR_TOP), rd16s(s + OFF_SCR_W),
                rd16s(s + OFF_SCR_H), rd8(s + OFF_SCR_BM + OFF_BM_DEPTH),
                cm ? rd32(cm + OFF_CM_MODEID) : 0xFFFFFFFFu, rd16(s + OFF_SCR_FLAGS),
                rd8s(s + OFF_SCR_BARH), rd8s(s + OFF_SCR_BARVB), rd8s(s + OFF_SCR_BARHB),
                rd8s(s + OFF_SCR_MENUVB), rd8s(s + OFF_SCR_MENUHB),
                rd8s(s + OFF_SCR_WBL), rd8s(s + OFF_SCR_WBT), rd8s(s + OFF_SCR_WBR), rd8s(s + OFF_SCR_WBB));
        jfont(f, rd32(s + OFF_SCR_RP + OFF_RP_FONT));
        fputs(",\"windows\":[", f);
        for (w = rd32(s + OFF_SCR_FIRSTWIN); w && wguard < 256; w = rd32(w + OFF_W_NEXT), wguard++) {
            if (!fw)
                fputc(',', f);
            jwindow(f, w);
            fw = 0;
        }
        fputs("]}", f);
        fs = 0;
    }
    fputs("]}\n", f);
    fclose(f);
    return 0;
}

/* ------------------------------------------------------------------ */
/* Pen-index capture (LXASNAP1)                                        */
/* ------------------------------------------------------------------ */

/* the front-most screen: what the user sees (agent: SNAP) */
static uint32_t active_screen(void)
{
    uint32_t ib = intuition_base();
    return ib ? rd32(ib + OFF_IB_FIRSTSCR) : 0;
}

static int read_pen(uint32_t bm, int depth, int x, int y)
{
    uint16_t bpr = rd16(bm + OFF_BM_BPR);
    int pen = 0, p;
    for (p = 0; p < depth; p++) {
        uint32_t plane = rd32(bm + OFF_BM_PLANES + p * 4);
        if (plane && (rd8(plane + (uint32_t)y * bpr + (x >> 3)) & (0x80 >> (x & 7))))
            pen |= 1 << p;
    }
    return pen;
}

static bool capture_indexed(uint32_t scr, int x0, int y0, int w, int h, const char *path)
{
    /* the screen RastPort's BitMap is authoritative (custom-bitmap screens) */
    uint32_t bm = rd32(scr + OFF_SCR_RP + OFF_RP_BITMAP);
    if (!bm)
        bm = scr + OFF_SCR_BM;
    int depth = rd8(bm + OFF_BM_DEPTH);
    int rows = rd16(bm + OFF_BM_ROWS), cols = rd16(bm + OFF_BM_BPR) * 8;
    int ncolors = 1 << (depth > 8 ? 8 : depth), i, x, y;
    FILE *f;
    unsigned char *line;

    if (w <= 0 || h <= 0 || depth <= 0)
        return false;
    f = fopen(path, "wb");
    if (!f)
        return false;
    fprintf(f, "LXASNAP1 %d %d %d %d\n", w, h, depth, ncolors);
    for (i = 0; i < ncolors; i++) {
        uint8_t rgb[3] = {0, 0, 0};
        lxa_get_palette_rgb(i, &rgb[0], &rgb[1], &rgb[2]);
        fwrite(rgb, 1, 3, f);
    }
    line = malloc((size_t)w);
    for (y = 0; y < h; y++) {
        for (x = 0; x < w; x++) {
            int sx = x0 + x, sy = y0 + y;
            line[x] = (sx >= 0 && sy >= 0 && sx < cols && sy < rows) ? (unsigned char)read_pen(bm, depth, sx, sy) : 0;
        }
        fwrite(line, 1, (size_t)w, f);
    }
    free(line);
    fclose(f);
    return true;
}

bool lxa_capture_screen_indexed(const char *path)
{
    uint32_t s = active_screen();
    if (!s || !path)
        return false;
    return capture_indexed(s, 0, 0, rd16s(s + OFF_SCR_W), rd16s(s + OFF_SCR_H), path);
}

bool lxa_capture_window_indexed(int index, const char *path)
{
    uint32_t s = active_screen(), w;
    int k = 0;
    if (!s || !path)
        return false;
    for (w = rd32(s + OFF_SCR_FIRSTWIN); w && k < index; w = rd32(w + OFF_W_NEXT))
        k++;
    if (!w)
        return false;
    return capture_indexed(s, rd16s(w + OFF_W_LEFT), rd16s(w + OFF_W_TOP),
                           rd16s(w + OFF_W_W), rd16s(w + OFF_W_H), path);
}

/* ------------------------------------------------------------------ */
/* Text() log                                                           */
/* ------------------------------------------------------------------ */

typedef struct { int16_t x, y; char s[61]; } text_rec_t;
static text_rec_t *s_text;
static int s_text_count, s_text_cap;

static void text_log_hook(const char *str, int len, int x, int y, void *ud)
{
    (void)ud;
    if (!s_text || s_text_count >= s_text_cap || !str || len <= 0)
        return;
    text_rec_t *r = &s_text[s_text_count++];
    if (len > 60)
        len = 60;
    memcpy(r->s, str, (size_t)len);
    r->s[len] = 0;
    r->x = (int16_t)x;
    r->y = (int16_t)y;
}

void lxa_text_log_start(void)
{
    if (!s_text) {
        s_text_cap = 8192;
        s_text = calloc((size_t)s_text_cap, sizeof(text_rec_t));
    }
    s_text_count = 0;
    lxa_set_text_hook(text_log_hook, NULL);
}

void lxa_text_log_stop(void)
{
    if (g_text_hook == text_log_hook)
        lxa_clear_text_hook();
}

int lxa_text_log_dump(const char *path)
{
    FILE *f = fopen(path, "w");
    int i;
    if (!f)
        return -1;
    for (i = 0; i < s_text_count; i++) {
        const unsigned char *c;
        fputs("{\"text\":\"", f);
        for (c = (const unsigned char *)s_text[i].s; *c; c++) {
            if (*c == '"' || *c == '\\')
                fprintf(f, "\\%c", *c);
            else if (*c < 0x20)
                fprintf(f, "\\u%04x", *c);
            else if (*c >= 0x80)
                fprintf(f, "%c%c", 0xC0 | (*c >> 6), 0x80 | (*c & 0x3F));
            else
                fputc(*c, f);
        }
        fprintf(f, "\",\"x\":%d,\"y\":%d}\n", s_text[i].x, s_text[i].y);
    }
    fclose(f);
    return s_text_count;
}
