/*
 * lxa_ndk_offsets.h - NDK struct field offsets for host-side code.
 * GENERATED by tools/gen_ndk_offsets.py (m68k-amigaos-gcc offsetof) - do not edit.
 */

#ifndef LXA_NDK_OFFSETS_H
#define LXA_NDK_OFFSETS_H

#define OFF_SCR_NEXT        0  /* struct Screen.NextScreen */
#define OFF_SCR_FIRSTWIN    4  /* struct Screen.FirstWindow */
#define OFF_SCR_LEFT        8  /* struct Screen.LeftEdge */
#define OFF_SCR_TOP        10  /* struct Screen.TopEdge */
#define OFF_SCR_W          12  /* struct Screen.Width */
#define OFF_SCR_H          14  /* struct Screen.Height */
#define OFF_SCR_TITLE      22  /* struct Screen.Title */
#define OFF_SCR_DEFTITLE   26  /* struct Screen.DefaultTitle */
#define OFF_SCR_BARH       30  /* struct Screen.BarHeight */
#define OFF_SCR_BARVB      31  /* struct Screen.BarVBorder */
#define OFF_SCR_BARHB      32  /* struct Screen.BarHBorder */
#define OFF_SCR_MENUVB     33  /* struct Screen.MenuVBorder */
#define OFF_SCR_MENUHB     34  /* struct Screen.MenuHBorder */
#define OFF_SCR_WBL        36  /* struct Screen.WBorLeft */
#define OFF_SCR_WBT        35  /* struct Screen.WBorTop */
#define OFF_SCR_WBR        37  /* struct Screen.WBorRight */
#define OFF_SCR_WBB        38  /* struct Screen.WBorBottom */
#define OFF_SCR_FLAGS      20  /* struct Screen.Flags */
#define OFF_SCR_VP         44  /* struct Screen.ViewPort */
#define OFF_SCR_RP         84  /* struct Screen.RastPort */
#define OFF_SCR_BM        184  /* struct Screen.BitMap */
#define OFF_VP_CM           4  /* struct ViewPort.ColorMap */
#define OFF_CM_MODEID      36  /* struct ColorMap.VPModeID */
#define OFF_CM_COUNT        2  /* struct ColorMap.Count */
#define OFF_CM_TABLE        4  /* struct ColorMap.ColorTable */
#define OFF_CM_LOWBITS     12  /* struct ColorMap.LowColorBits */
#define OFF_CM_TYPE         1  /* struct ColorMap.Type */
#define OFF_RP_FONT        52  /* struct RastPort.Font */
#define OFF_RP_BITMAP       4  /* struct RastPort.BitMap */
#define OFF_BM_BPR          0  /* struct BitMap.BytesPerRow */
#define OFF_BM_ROWS         2  /* struct BitMap.Rows */
#define OFF_BM_DEPTH        5  /* struct BitMap.Depth */
#define OFF_BM_PLANES       8  /* struct BitMap.Planes */
#define OFF_TF_NAME        10  /* struct TextFont.tf_Message.mn_Node.ln_Name */
#define OFF_TF_YSIZE       20  /* struct TextFont.tf_YSize */
#define OFF_TF_XSIZE       24  /* struct TextFont.tf_XSize */
#define OFF_TF_BASELINE    26  /* struct TextFont.tf_Baseline */
#define OFF_W_NEXT          0  /* struct Window.NextWindow */
#define OFF_W_LEFT          4  /* struct Window.LeftEdge */
#define OFF_W_TOP           6  /* struct Window.TopEdge */
#define OFF_W_W             8  /* struct Window.Width */
#define OFF_W_H            10  /* struct Window.Height */
#define OFF_W_MINW         16  /* struct Window.MinWidth */
#define OFF_W_MINH         18  /* struct Window.MinHeight */
#define OFF_W_MAXW         20  /* struct Window.MaxWidth */
#define OFF_W_MAXH         22  /* struct Window.MaxHeight */
#define OFF_W_FLAGS        24  /* struct Window.Flags */
#define OFF_W_MENU         28  /* struct Window.MenuStrip */
#define OFF_W_TITLE        32  /* struct Window.Title */
#define OFF_W_RPORT        50  /* struct Window.RPort */
#define OFF_W_BL           54  /* struct Window.BorderLeft */
#define OFF_W_BT           55  /* struct Window.BorderTop */
#define OFF_W_BR           56  /* struct Window.BorderRight */
#define OFF_W_BB           57  /* struct Window.BorderBottom */
#define OFF_W_FIRSTGAD     62  /* struct Window.FirstGadget */
#define OFF_W_DETAIL       98  /* struct Window.DetailPen */
#define OFF_W_BLOCK        99  /* struct Window.BlockPen */
#define OFF_W_IDCMP        82  /* struct Window.IDCMPFlags */
#define OFF_W_SCRTITLE    104  /* struct Window.ScreenTitle */
#define OFF_W_WSCREEN      46  /* struct Window.WScreen */
#define OFF_G_NEXT          0  /* struct Gadget.NextGadget */
#define OFF_G_LEFT          4  /* struct Gadget.LeftEdge */
#define OFF_G_TOP           6  /* struct Gadget.TopEdge */
#define OFF_G_W             8  /* struct Gadget.Width */
#define OFF_G_H            10  /* struct Gadget.Height */
#define OFF_G_FLAGS        12  /* struct Gadget.Flags */
#define OFF_G_ACT          14  /* struct Gadget.Activation */
#define OFF_G_TYPE         16  /* struct Gadget.GadgetType */
#define OFF_G_TEXT         26  /* struct Gadget.GadgetText */
#define OFF_G_ID           38  /* struct Gadget.GadgetID */
#define OFF_IT_FPEN         0  /* struct IntuiText.FrontPen */
#define OFF_IT_BPEN         1  /* struct IntuiText.BackPen */
#define OFF_IT_DMODE        2  /* struct IntuiText.DrawMode */
#define OFF_IT_LEFT         4  /* struct IntuiText.LeftEdge */
#define OFF_IT_TOP          6  /* struct IntuiText.TopEdge */
#define OFF_IT_TEXT        12  /* struct IntuiText.IText */
#define OFF_IT_NEXT        16  /* struct IntuiText.NextText */
#define OFF_M_NEXT          0  /* struct Menu.NextMenu */
#define OFF_M_LEFT          4  /* struct Menu.LeftEdge */
#define OFF_M_TOP           6  /* struct Menu.TopEdge */
#define OFF_M_W             8  /* struct Menu.Width */
#define OFF_M_H            10  /* struct Menu.Height */
#define OFF_M_FLAGS        12  /* struct Menu.Flags */
#define OFF_M_NAME         14  /* struct Menu.MenuName */
#define OFF_M_FIRST        18  /* struct Menu.FirstItem */
#define OFF_MI_NEXT         0  /* struct MenuItem.NextItem */
#define OFF_MI_LEFT         4  /* struct MenuItem.LeftEdge */
#define OFF_MI_TOP          6  /* struct MenuItem.TopEdge */
#define OFF_MI_W            8  /* struct MenuItem.Width */
#define OFF_MI_H           10  /* struct MenuItem.Height */
#define OFF_MI_FLAGS       12  /* struct MenuItem.Flags */
#define OFF_MI_MX          14  /* struct MenuItem.MutualExclude */
#define OFF_MI_FILL        18  /* struct MenuItem.ItemFill */
#define OFF_MI_CMD         26  /* struct MenuItem.Command */
#define OFF_MI_SUB         28  /* struct MenuItem.SubItem */
#define OFF_IB_FIRSTSCR    60  /* struct IntuitionBase.FirstScreen */
#define OFF_IB_ACTWIN      52  /* struct IntuitionBase.ActiveWindow */
#define OFF_IB_ACTSCR      56  /* struct IntuitionBase.ActiveScreen */

#endif /* LXA_NDK_OFFSETS_H */
