"""Shallow sweep & divergence ranking (Phase 231).

    python3 -m rdd sweep gen                     # tests/scenarios/sweep/<app>.yaml
    python3 -m rdd sweep run  [--out DIR] [-j N] # twin run + report + rank + cluster
    python3 -m rdd sweep rank [--out DIR] [--md FILE]

The sweep scenario of an app is its Phase 230 launch scenario
(tests/scenarios/apps/<app>.yaml) plus `menus` (open every menu of the
window and snapshot it) before quitting.  `rank` orders the apps by the
severity of their worst divergence:

    crash (lxa failed a step the reference passed) > no window > tree diff > pixel diff

and clusters all divergences across apps (`rdd cluster`); clusters seen in
>= 2 apps without an owning phase get phase stubs (compat-sweep skill).
"""

import argparse
import datetime
import glob
import json
import os
import re
import subprocess
import sys

from rdd.scenario import ROOT

APPS_SCN = os.path.join(ROOT, "tests", "scenarios", "apps")
SWEEP_SCN = os.path.join(ROOT, "tests", "scenarios", "sweep")
OUT = os.path.join(ROOT, "build", "rdd", "sweep")


def gen():
    os.makedirs(SWEEP_SCN, exist_ok=True)
    n = 0
    for src in sorted(glob.glob(os.path.join(APPS_SCN, "*.yaml"))):
        with open(src) as f:
            text = f.read()
        text = re.sub(r"^name: app-", "name: sweep-", text, flags=re.M)
        text = re.sub(r"^# .*\n(# .*\n)*", "# Phase 231 sweep scenario, generated from tests/scenarios/apps/%s\n"
                      "# by `python3 -m rdd sweep gen` - edit the app scenario, not this file.\n"
                      % os.path.basename(src), text, count=1)
        if "  - menus" not in text:
            text = re.sub(r"^  - quit", "  - menus\n  - quit", text, flags=re.M)
        with open(os.path.join(SWEEP_SCN, os.path.basename(src)), "w") as f:
            f.write(text)
        n += 1
    print("%d sweep scenarios in %s" % (n, os.path.relpath(SWEEP_SCN, ROOT)))


SEVERITY = ["crash", "no-window", "tree", "pixels", "identical", "untested"]


def app_severity(run, scn):
    sdir = os.path.join(run, scn)
    try:
        with open(os.path.join(sdir, "lxa", "result.json")) as f:
            lx = json.load(f)
        with open(os.path.join(sdir, "ref", "result.json")) as f:
            rf = json.load(f)
    except OSError:
        return "untested", {}
    if not rf.get("ok"):
        return "untested", {"reason": "reference run failed: %s" % _first_error(rf)}
    if not lx.get("ok"):
        err = _first_error(lx)
        kind = "no-window" if "no window" in err else "crash"
        return kind, {"reason": err}
    worst = "identical"
    diffs = {"tree": 0, "pixels": 0, "snapshots": 0}
    for snap in lx.get("snapshots", []):
        cp = os.path.join(sdir, "compare", snap, "compare.json")
        if not os.path.exists(cp):
            continue
        with open(cp) as f:
            c = json.load(f)
        diffs["snapshots"] += 1
        diffs["tree"] += len(c["tree"])
        diffs["pixels"] += (c.get("pixels") or {}).get("diff_pixels") or 0
        v = c["verdict"]
        v = "pixels" if v == "output" else v
        if SEVERITY.index(v) < SEVERITY.index(worst):
            worst = v
    return worst, diffs


def _first_error(res):
    for st in res.get("steps", []):
        if not st.get("ok"):
            return "%s: %s" % (st["step"], st.get("error"))
    return res.get("error", "?")


def rank(out, md=None, first_phase=290):
    from rdd import cluster
    rows = []
    for scn in sorted(os.listdir(out)):
        if not os.path.isdir(os.path.join(out, scn, "lxa")):
            continue
        sev, info = app_severity(out, scn)
        rows.append({"scenario": scn, "severity": sev, **info})
    rows.sort(key=lambda r: (SEVERITY.index(r["severity"]), -r.get("tree", 0), -r.get("pixels", 0)))
    findings = sorted(glob.glob(os.path.join(ROOT, "doc", "findings", "*.yaml")))
    cl = cluster.cluster_run(out, findings) if os.path.exists(os.path.join(out, "compare-summary.json")) else []
    stubs = cluster.phase_stubs(cl, first_phase)
    with open(os.path.join(out, "sweep-rank.json"), "w") as f:
        json.dump({"apps": rows, "clusters": cl}, f, indent=1)
    if md:
        today = datetime.date.today().isoformat()
        L = ["# Shallow sweep %s" % today, "",
             "Generated by `python3 -m rdd sweep run` (Phase 231): every corpus app launched on lxa and on "
             "AmigaOS 3.1, snapshot at startup and with each menu open.", "",
             "## Apps by worst divergence", "", "| app | worst | tree diffs | differing pixels | note |",
             "|---|---|---|---|---|"]
        for r in rows:
            L.append("| %s | %s | %s | %s | %s |" % (r["scenario"].replace("sweep-", ""), r["severity"],
                                                    r.get("tree", ""), r.get("pixels", ""),
                                                    (r.get("reason") or "").replace("|", "/")[:100]))
        L += ["", "## Divergence clusters seen in >= 2 apps", "",
              "| apps | owner | signature | suspect |", "|---|---|---|---|"]
        L += ["| %d | %s | %s | %s |" % (len(c["apps"]), ", ".join(map(str, c["phases"])) or "**unowned**",
                                        c["signature"].replace("|", "/")[:110], " / ".join(c["suspect"] or []))
              for c in cl if len(c["apps"]) >= 2]
        L += ["", "## Phase stubs for unowned clusters", "", stubs.split("\n", 3)[-1]]
        with open(md, "w") as f:
            f.write("\n".join(L) + "\n")
    return rows, cl


def main(argv=None):
    ap = argparse.ArgumentParser(prog="rdd sweep")
    ap.add_argument("cmd", choices=["gen", "run", "rank"])
    ap.add_argument("--out", default=OUT)
    ap.add_argument("-j", "--jobs", type=int, default=6)
    ap.add_argument("--build")
    ap.add_argument("--md")
    ap.add_argument("--filter")
    a = ap.parse_args(argv)
    a.out = os.path.abspath(a.out)
    if a.cmd == "gen":
        gen()
        return 0
    if a.cmd == "run":
        scns = sorted(glob.glob(os.path.join(SWEEP_SCN, "*.yaml")))
        if a.filter:
            scns = [s for s in scns if re.search(a.filter, s)]
        env = dict(os.environ, PYTHONPATH=os.path.join(ROOT, "tools"))
        cmd = [sys.executable, "-m", "rdd", "run", *scns, "--out", a.out, "-j", str(a.jobs)]
        if a.build:
            cmd += ["--build", os.path.abspath(a.build)]
        subprocess.run(cmd, env=env, cwd=os.path.join(ROOT, "tools"))
        subprocess.run([sys.executable, "-m", "rdd", "report", a.out], env=env, cwd=os.path.join(ROOT, "tools"),
                       stdout=subprocess.DEVNULL)
    rows, cl = rank(a.out, a.md and os.path.abspath(a.md))
    for r in rows:
        print("%-28s %-10s %s" % (r["scenario"], r["severity"], r.get("reason", "")[:90]))
    multi = [c for c in cl if len(c["apps"]) >= 2]
    print("%d apps; %d clusters in >= 2 apps, %d unowned" % (len(rows), len(multi),
                                                           sum(1 for c in multi if not c["owned"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
