"""Generate src/rom/lxa_sysi_data.h from the sysiclass gallery reference (Phase 223).

    python3 -m rdd.sysitable <normal-bundle> <bg-bundle> [-o src/rom/lxa_sysi_data.h]

<normal-bundle>/<bg-bundle> are the reference snapshot bundles of
tests/scenarios/gallery-sysimages.yaml and gallery-sysimages-bg.yaml (the
golden copies live in tests/golden/SysI/).  The gallery draws every
SYSIA_Which x SYSIA_Size image of real AmigaOS 3.1 in the states
IDS_NORMAL, IDS_SELECTED, IDS_INACTIVENORMAL and IDS_DISABLED, once on pen 0
and once on pen 3; the generator turns each image into a table of pen roles:

    '-' not drawn     'B' BACKGROUNDPEN   'S' SHINEPEN     'D' SHADOWPEN
    'F' FILLPEN       'K' BARDETAILPEN    'L' BARBLOCKPEN

This is black-box observation of rendered output (RDD clean-room rule): the
reference is run, its pixels are read back, nothing else.
"""

import argparse
import os
import re
import sys

from rdd.bundle import read_palette_png

WHICH = [0, 1, 2, 3, 5, 10, 11, 12, 13, 14, 15, 16, 17]
MENU_IMAGES = (16, 17)          # drawn in the menu (bar) pens
STATES = ("N", "S", "I", "D")
CELLW, CELLH = 44, 17
BL, BT = 4, 11                  # window border of the gallery window


def load(bundle):
    w, h, pens = read_palette_png(os.path.join(bundle, "screen.png"))
    sizes = {}
    with open(os.path.join(bundle, "stdout.txt")) as f:
        for ln in f:
            m = re.match(r"which (\d+) size (\d+): (\d+)x(\d+)", ln)
            if m:
                sizes[(int(m.group(1)), int(m.group(2)))] = (int(m.group(3)), int(m.group(4)))
    return (lambda x, y: pens[y * w + x]), sizes


def role(which, pen):
    if which in MENU_IMAGES:
        return {1: "K", 2: "L", 0: "B", 3: "F"}[pen]
    return {0: "B", 1: "D", 2: "S", 3: "F"}[pen]


def cell(px, bg, which, wi, si, st, W, H):
    """the image cell plus a one-pixel margin (images may draw outside
    their Width/Height, e.g. the depth gadget's separator at x = -1)"""
    out = []
    for y in range(-1, H + 1):
        for x in range(-1, W + 1):
            X = BL + 4 + wi * CELLW + x
            Y = BT + 2 + (((si * 4 + st) * CELLH) if si < 2 else (8 * CELLH + st * 23)) + y
            p, q = px(X, Y), bg(X, Y)
            out.append("-" if (p == 0 and q == 3) else role(which, p))
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("normal")
    ap.add_argument("bg")
    ap.add_argument("-o", default=None)
    a = ap.parse_args()
    px, sizes = load(a.normal)
    bg, _ = load(a.bg)
    pool, entries = {}, []

    def ref(s):
        if s not in pool:
            pool[s] = len(pool)
        return pool[s]

    for si in range(3):
        for wi, w in enumerate(WHICH):
            W, H = sizes[(w, si)]
            st = [cell(px, bg, w, wi, si, k, W, H) for k in range(4)]
            CW = W + 2
            xs = [i % CW for s_ in st for i, c in enumerate(s_) if c != "-"]
            ys = [i // CW for s_ in st for i, c in enumerate(s_) if c != "-"]
            x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
            crop = ["".join(s_[y * CW + x0:y * CW + x1 + 1] for y in range(y0, y1 + 1)) for s_ in st]
            entries.append((w, si, W, H, x0 - 1, y0 - 1, x1 - x0 + 1, y1 - y0 + 1,
                            [ref(s_) for s_ in crop]))

    lines = ["/* Generated by tools/rdd/sysitable.py from the AmigaOS 3.1 reference",
             " * renderings of tests/scenarios/gallery-sysimages*.yaml (Phase 223).",
             " * Do not edit; re-generate from the golden reference bundles. */",
             "", "#ifndef LXA_SYSI_DATA_H", "#define LXA_SYSI_DATA_H", ""]
    # pool: run-length packed bytes: (count << 3) | role, count 1..31
    codes = "-BSDFKL"
    lines.append("static const UBYTE g_sysi_pixels[] = {")
    offsets = []
    total = 0
    for s, _ in sorted(pool.items(), key=lambda kv: kv[1]):
        offsets.append(total)
        b = []
        i = 0
        while i < len(s):
            j = i
            while j < len(s) and s[j] == s[i] and j - i < 31:
                j += 1
            b.append(((j - i) << 3) | codes.index(s[i]))
            i = j
        total += len(b)
        lines.append("    " + ", ".join(str(v) for v in b) + ",")
    lines.append("};")
    lines.append("")
    lines.append("static const UWORD g_sysi_offsets[] = { %s };" % ", ".join(str(o) for o in offsets))
    lines.append("")
    lines.append("/* width/height: the image size (IA_Width/IA_Height); the bitmap is dw x dh")
    lines.append(" * pixels drawn at (dx, dy) relative to the image position */")
    lines.append("struct LXASysIEntry { UBYTE which, size, width, height; BYTE dx, dy; UBYTE dw, dh; UWORD state[4]; };")
    lines.append("")
    lines.append("/* states: IDS_NORMAL, IDS_SELECTED, IDS_INACTIVENORMAL, IDS_DISABLED */")
    lines.append("static const struct LXASysIEntry g_sysi_entries[] = {")
    for w, si, W, H, dx, dy, dw, dh, st in entries:
        lines.append("    { %d, %d, %d, %d, %d, %d, %d, %d, { %s } }," % (w, si, W, H, dx, dy, dw, dh,
                                                                      ", ".join(str(x) for x in st)))
    lines.append("};")
    lines.append("")
    lines.append("#define LXA_SYSI_ROLE_NONE 0  /* roles: %s */" % codes)
    lines.append("")
    lines.append("#endif")
    text = "\n".join(lines) + "\n"
    if a.o:
        with open(a.o, "w") as f:
            f.write(text)
        print("%s: %d images, %d distinct bitmaps, %d bytes" % (a.o, len(entries), len(pool), total))
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
