#!/usr/bin/env python3
"""Generate src/lxa/lxa_ndk_offsets.h: NDK struct field offsets for host code.

Host code (liblxa) reads Intuition/graphics structures from emulated memory.
Instead of hand-written offsets, the m68k cross compiler computes them with
offsetof() from the NDK headers.

  tools/gen_ndk_offsets.py            # rewrite the header
"""
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GCC = os.environ.get("M68K_GCC", "/opt/amiga/bin/m68k-amigaos-gcc")

FIELDS = """
SCR_NEXT Screen NextScreen; SCR_FIRSTWIN Screen FirstWindow; SCR_LEFT Screen LeftEdge; SCR_TOP Screen TopEdge
SCR_W Screen Width; SCR_H Screen Height; SCR_TITLE Screen Title; SCR_DEFTITLE Screen DefaultTitle
SCR_BARH Screen BarHeight; SCR_BARVB Screen BarVBorder; SCR_BARHB Screen BarHBorder; SCR_MENUVB Screen MenuVBorder
SCR_MENUHB Screen MenuHBorder; SCR_WBL Screen WBorLeft; SCR_WBT Screen WBorTop; SCR_WBR Screen WBorRight
SCR_WBB Screen WBorBottom; SCR_FLAGS Screen Flags; SCR_VP Screen ViewPort; SCR_RP Screen RastPort; SCR_BM Screen BitMap
VP_CM ViewPort ColorMap; CM_MODEID ColorMap VPModeID
RP_FONT RastPort Font; RP_BITMAP RastPort BitMap
BM_BPR BitMap BytesPerRow; BM_ROWS BitMap Rows; BM_DEPTH BitMap Depth; BM_PLANES BitMap Planes
TF_NAME TextFont tf_Message.mn_Node.ln_Name; TF_YSIZE TextFont tf_YSize; TF_XSIZE TextFont tf_XSize; TF_BASELINE TextFont tf_Baseline
W_NEXT Window NextWindow; W_LEFT Window LeftEdge; W_TOP Window TopEdge; W_W Window Width; W_H Window Height
W_MINW Window MinWidth; W_MINH Window MinHeight; W_MAXW Window MaxWidth; W_MAXH Window MaxHeight
W_FLAGS Window Flags; W_MENU Window MenuStrip; W_TITLE Window Title; W_RPORT Window RPort
W_BL Window BorderLeft; W_BT Window BorderTop; W_BR Window BorderRight; W_BB Window BorderBottom
W_FIRSTGAD Window FirstGadget; W_DETAIL Window DetailPen; W_BLOCK Window BlockPen; W_IDCMP Window IDCMPFlags
W_SCRTITLE Window ScreenTitle; W_WSCREEN Window WScreen
G_NEXT Gadget NextGadget; G_LEFT Gadget LeftEdge; G_TOP Gadget TopEdge; G_W Gadget Width; G_H Gadget Height
G_FLAGS Gadget Flags; G_ACT Gadget Activation; G_TYPE Gadget GadgetType; G_TEXT Gadget GadgetText; G_ID Gadget GadgetID
IT_FPEN IntuiText FrontPen; IT_BPEN IntuiText BackPen; IT_DMODE IntuiText DrawMode; IT_LEFT IntuiText LeftEdge
IT_TOP IntuiText TopEdge; IT_TEXT IntuiText IText; IT_NEXT IntuiText NextText
M_NEXT Menu NextMenu; M_LEFT Menu LeftEdge; M_TOP Menu TopEdge; M_W Menu Width; M_H Menu Height
M_FLAGS Menu Flags; M_NAME Menu MenuName; M_FIRST Menu FirstItem
MI_NEXT MenuItem NextItem; MI_LEFT MenuItem LeftEdge; MI_TOP MenuItem TopEdge; MI_W MenuItem Width
MI_H MenuItem Height; MI_FLAGS MenuItem Flags; MI_MX MenuItem MutualExclude; MI_FILL MenuItem ItemFill
MI_CMD MenuItem Command; MI_SUB MenuItem SubItem
IB_FIRSTSCR IntuitionBase FirstScreen; IB_ACTWIN IntuitionBase ActiveWindow; IB_ACTSCR IntuitionBase ActiveScreen
"""


def main():
    fields = [f.split() for f in re.split(r"[;\n]", FIELDS) if f.strip()]
    src = ["#include <intuition/intuition.h>", "#include <intuition/screens.h>",
           "#include <intuition/intuitionbase.h>", "#include <graphics/text.h>",
           "#include <graphics/view.h>", "#include <stddef.h>"]
    # +1 so no value is 0 (zero-initialised globals would go to .comm)
    src += ["int %s = offsetof(struct %s, %s) + 1;" % (n, s, f) for n, s, f in fields]
    with tempfile.NamedTemporaryFile("w", suffix=".c", delete=False) as t:
        t.write("\n".join(src) + "\n")
        path = t.name
    asm = subprocess.run([GCC, "-S", "-o", "-", path], capture_output=True, text=True, check=True).stdout
    os.unlink(path)
    vals = {}
    cur = None
    for line in asm.splitlines():
        m = re.match(r"^_(\w+):", line)
        if m:
            cur = m.group(1)
            continue
        m = re.match(r"\s+\.long\s+(\d+)", line)
        if m and cur:
            vals[cur] = int(m.group(1)) - 1
            cur = None
    missing = [n for n, _, _ in fields if n not in vals]
    if missing:
        sys.exit("gen_ndk_offsets: no value for %s" % missing)
    out = ["/*", " * lxa_ndk_offsets.h - NDK struct field offsets for host-side code.",
           " * GENERATED by tools/gen_ndk_offsets.py (m68k-amigaos-gcc offsetof) - do not edit.",
           " */", "", "#ifndef LXA_NDK_OFFSETS_H", "#define LXA_NDK_OFFSETS_H", ""]
    out += ["#define OFF_%-12s %4d  /* struct %s.%s */" % (n, vals[n], s, f) for n, s, f in fields]
    out += ["", "#endif /* LXA_NDK_OFFSETS_H */", ""]
    with open(os.path.join(ROOT, "src", "lxa", "lxa_ndk_offsets.h"), "w") as f:
        f.write("\n".join(out))
    print("gen_ndk_offsets: %d offsets" % len(fields))


if __name__ == "__main__":
    main()
