#!/usr/bin/env python3
"""Static inventory of every stub / partial implementation (Phase 203).

Lists every LXA_UNIMPLEMENTED(lib, fn, detail) site, every
PRIVATE_FUNCTION_ERROR slot and the empty exec vectors, and writes the
authoritative M5 work list to doc/stub-inventory.md (+ .json).

  tools/stub_inventory.py [--check]

--check  exit 1 if doc/stub-inventory.md is out of date (for CI).
"""

import argparse
import glob
import json
import os
import re
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MACRO = re.compile(r'LXA_UNIMPLEMENTED\(\s*"([^"]*)"\s*,\s*("([^"]*)"|\w+)\s*,\s*"([^"]*)"\s*\)')
PRIVATE = re.compile(r'PRIVATE_FUNCTION_ERROR\(\s*"_?([^"]*)"\s*,\s*"([^"]*)"\s*\)')
FUNC_DEF = re.compile(r'^[A-Za-z][\w \*]*?\b(\w+)\s*\(', re.M)


def enclosing_function(src, pos):
    best = None
    for m in FUNC_DEF.finditer(src, 0, pos):
        best = m.group(1)
    return best or "?"


def scan():
    sites = []
    for path in sorted(glob.glob(os.path.join(ROOT, "src", "rom", "*.c"))):
        src = open(path, errors="replace").read()
        rel = os.path.relpath(path, ROOT)
        for m in MACRO.finditer(src):
            if src.rfind("#define", 0, m.start()) > src.rfind("\n", 0, m.start()):
                continue
            line = src.count("\n", 0, m.start()) + 1
            fn = m.group(3) if m.group(3) is not None else "<%s>" % m.group(2)
            detail = m.group(4)
            kind = detail.split(":", 1)[0] if ":" in detail else "stub"
            sites.append({"lib": m.group(1), "function": fn, "kind": kind,
                          "detail": detail, "file": rel, "line": line,
                          "symbol": enclosing_function(src, m.start())})
        for m in PRIVATE.finditer(src):
            line = src.count("\n", 0, m.start()) + 1
            fn = m.group(2)
            if fn in ("ExtFuncLib", "Reserved"):
                continue    # library-base reserved vector, not an API function
            sites.append({"lib": m.group(1), "function": fn, "kind": "private",
                          "detail": "private/reserved slot", "file": rel, "line": line,
                          "symbol": enclosing_function(src, m.start())})
    return sites


def missing_lvos(build):
    """LVOs of tracked system libraries with no ROM symbol (needs a build)."""
    sys.path.insert(0, os.path.join(ROOT, "tools"))
    try:
        import coverage_report as cr
    except ImportError:
        return []
    rom_dir = os.path.join(build, "target", "rom")
    if not os.path.exists(os.path.join(rom_dir, "lxa.rom.map")):
        return []
    symbols = {}
    for base, obj in cr.rom_objects(build):
        if os.path.exists(obj):
            symbols[os.path.basename(obj)] = {k: True for k in cr.object_functions(obj)}
    table = cr.lvo_table(symbols, ROOT, measured=False, disk_hits=None)
    return [e for e in table if e["status"] == "no ROM symbol"]


def render(sites, missing=None):
    by_lib = defaultdict(list)
    for s in sites:
        by_lib[s["lib"]].append(s)
    out = ["# Stub inventory", "",
           "Generated by `tools/stub_inventory.py` (Phase 203). Every entry reports at",
           "runtime through `LXA_UNIMPLEMENTED` (EMU_CALL_UNIMPLEMENTED): hits are",
           "counted, logged once, summarised in `lxa.log`, available through",
           "`lxa_get_unimplemented_log()`, and stop the run under",
           "`--strict-unimplemented` / `lxa_config_t.strict_unimplemented`.",
           "Empty exec.library vectors report as `exec/LVO -nnn`.",
           "",
           "This list is the authoritative work list for M5. Remove an entry by",
           "implementing the function, never by deleting the macro.",
           "",
           "| Library | stub | partial | private slot |", "|---|---|---|---|"]
    tot = defaultdict(int)
    for lib in sorted(by_lib):
        c = defaultdict(int)
        for s in by_lib[lib]:
            c[s["kind"]] += 1
            tot[s["kind"]] += 1
        out.append("| %s | %d | %d | %d |" % (lib, c["stub"], c["partial"], c["private"]))
    out.append("| **total** | **%d** | **%d** | **%d** |" % (tot["stub"], tot["partial"], tot["private"]))
    out.append("")
    for lib in sorted(by_lib):
        out.append("## %s" % lib)
        out.append("")
        for s in sorted(by_lib[lib], key=lambda x: (x["kind"], x["function"])):
            out.append("- `%s` — %s (`%s:%d`)" % (s["function"], s["detail"], s["file"], s["line"]))
        out.append("")
    if missing:
        out.append("## LVOs without any implementation")
        out.append("")
        out.append("Public LVOs (NDK 3.2 pragmas, so V44+ functions are included) for which")
        out.append("no ROM function exists; calls land in an empty vector. Resources and")
        out.append("libraries lxa does not provide at all are listed in full.")
        out.append("")
        per = defaultdict(list)
        for e in missing:
            per[e["lib"]].append("%s (%d)" % (e["function"], e["lvo"]))
        for lib in sorted(per):
            out.append("- **%s**: %s" % (lib, ", ".join(per[lib])))
        out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--build", default=os.path.join(ROOT, "build"))
    a = ap.parse_args()
    sites = scan()
    missing = missing_lvos(a.build)
    md = render(sites, missing)
    md_path = os.path.join(ROOT, "doc", "stub-inventory.md")
    if a.check:
        cur = open(md_path).read() if os.path.exists(md_path) else ""
        if cur.strip() != md.strip():
            print("doc/stub-inventory.md is out of date: run tools/stub_inventory.py", file=sys.stderr)
            return 1
        return 0
    with open(md_path, "w") as f:
        f.write(md + "\n")
    with open(os.path.join(ROOT, "doc", "stub-inventory.json"), "w") as f:
        json.dump(sites, f, indent=1)
    kinds = defaultdict(int)
    for s in sites:
        kinds[s["kind"]] += 1
    print("stub inventory: %d sites (%d stub, %d partial, %d private), %d LVOs without implementation"
          " -> doc/stub-inventory.md" % (len(sites), kinds["stub"], kinds["partial"], kinds["private"], len(missing)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
